export enum RoomSocketEvents {
  ROOM_JOIN = 'ROOM_JOIN',
  ROOM_JOIN_ERROR = 'ROOM_JOIN_ERROR',
  ROOM_DATA = 'ROOM_DATA',
  ROOM_USERS = 'ROOM_USERS',
  ROOM_RESULTS = 'ROOM_RESULTS',
  START_QUIZ = 'START_QUIZ',
  SET_READY = 'SET_READY',
  SUBMIT_ANSWERS = 'SUBMIT_ANSWERS',
  ROOM_LEAVE = 'ROOM_LEAVE',
}
